VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    config.vm.hostname = "roletest"

    config.vm.provider "virtualbox" do |v|
        v.name = "roletest"
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.provision "ansible", run: "always" do |ansible|
        ansible.playbook = "test.yml"
        ansible.verbose = "vvv"
        ansible.inventory_path = "inventory"
        ansible.limit = "all"
    end


    config.vm.network "private_network", ip: "10.1.0.2"
    # config.vm.network "forwarded_port", guest: 80, host: 80
    # config.vm.network "forwarded_port", guest: 443, host: 443

end
