- name: Configure user root
  mysql_user:
    user: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  ignore_errors: yes

- name: generate root credentials
  template:
    src: root-my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: Create databases
  with_items:
  - "{{ mysql_databases }}"
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present

- name: configure users
  mysql_user:
    append_privs: "{{ mysql_append_privs | default('no')}}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
    host: "{{ item.host | default('localhost') }}"
  with_items:
  - "{{ mysql_users }}"

- name: flush privileges
  command: 'mysql -u root -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES;"'

- name: Remove anonymous user
  mysql_user:
    name: ""
    state: absent

- name: Remove test database
  mysql_db:
    name: test
    state: absent
