- name: install common packages
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
  - software-properties-common
  - python-mysqldb

- name: add repo key
  apt_key:
    keyserver: pgp.mit.edu
    id: '5072E1F5'

- name: add repo
  apt_repository:
    repo: deb http://repo.mysql.com/apt/debian stretch mysql-5.7
    state: present

- name: install packages
  apt:
    update_cache: yes
    name: mysql-server
    state: latest

- name: enable service
  service:
    name: mysql
    state: started
    enabled: yes
