# target and year are defined in vagrant
develop: yes
pm2_user: vagrant
pm2_npm_tasks: yes
pm2_apps:
- name: kaos-scraper
  extra_opts:
  script: 'app.js'
  instances: 1
  mode: fork
  path: /vagrant/App
  args:
  - SCRAP
  - BOE
  - 2011
  env:
    KAOS_MYSQL_SCRAP_PASS: password
    KAOS_MYSQL_SCRAP_USER: kaos
    KAOS_MYSQL_SCRAP_HOST: localhost
    KAOS_MYSQL_SCRAP_DB: bbdd_kaos155_text
